name: CI Practice

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show system info
        run: |
          echo "Дата: $(date)"
          echo "ОС: $(uname -a)"
          df -h

      - name: Run a simple test
        run: |
          echo "Создаём тестовый файл..."
          echo "hello" > test.txt
          if [ "$(cat test.txt)" = "hello" ]; then
            echo "✅ Тест пройден"
          else
            echo "❌ Тест провален"
            exit 1
          fi
