name: Artifact Practice

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Создаём тестовые файлы
        run: |
          mkdir -p ./reports
          echo "Дата сборки: $(date)" > ./reports/build-info.txt
          echo "Статус: УСПЕХ" >> ./reports/build-info.txt
          df -h > ./reports/disk-usage.txt

      - name: Сохраняем артефакт
        uses: actions/upload-artifact@v4
        with:
          name: build-report
          path: ./reports/

  test:
    needs: build  # ждём завершения job 'build'
    runs-on: ubuntu-latest
    steps:
      - name: Загружаем артефакт
        uses: actions/download-artifact@v4
        with:
          name: build-report
          path: ./downloaded-reports

      - name: Показываем содержимое
        run: |
          echo "=== Содержимое артефакта ==="
          cat ./downloaded-reports/build-info.txt
          cat ./downloaded-reports/disk-usage.txt
